import React from "react";
import "./navlayout.css";
import Navigation from "../component/Navigation/Navigation";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// export default function NavigationLayout({ children }) {
//     return (
//         <div className="nav-layout-wrapper">
//             <Navigation />
//             <div className="content-wrapper">{children}</div>
//         </div>
//     );
// }
export default function NavigationLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="nav-layout-wrapper">
            <Navigation />
            <div className="content-wrapper">{children}</div>
        </div>
    );
}
